### ISSUE TITLE
[teeracle] authenticate sources with hard-coded certificates

### ISSUE THREAD

**Issue by brenzi** [integritee-network/teeracle#1]
currently, we open a TLS connection to coingecko, but we do not check the certificate, so we do not feature non-repudiation currently. This should be implemented by hard-coding the coingecko certificate(s) and verifying them when opening a TLS connection

It could be that one teeracle enclave operates more than one source (coinmarketcap, see pallets#25

**Comment by echevrier** [comment]
### Teeracle https connection configuration check
Teeracle connect uses `itc-rest-client::HttpClient`

**itc-rest-client::HttpClient**
 uses `http_req = { version = "0.7", optional = true, default-features = false, features = ["rust-tls"] }`

**http_req**
 uses rustls :
```
      [dependencies.rustls]
      version = "^0.19"
      optional = true
``` 
-> rustls hasn't the features = ["dangerous_configuration"].

-> **Self-signed certificate are blocked.**

**Comment by echevrier** [comment]
### Certificates validation
**http_req**
`Request.send` -> 
    add a root certificate in the trusted root store, if it is desired. To do it call Request `root_cert_file_pem`(...) with a file containing the PEM-encoded certificates that should be added.
   connect over tls : `Config.connect` -> `rustls::ClientSession`
->  Only default root certificate are set: `webpki_roots::TLS_SERVER_ROOTS`, which contains the Mozilla set of root certificates.
      See: https://github.com/rustls/webpki-roots

**Comment by echevrier** [comment]
Let's Encrypt certificates ISRG Root X1 are allowed:
see https://github.com/integritee-network/teeracle/issues/3# 

To fix it, we have to change the trusted root store in http_req.

**Comment by brenzi** [comment]
Please file an issue for what needs to be done to fix this one
