### ISSUE TITLE
release teeracle SDK

### ISSUE THREAD

**Issue by brenzi** [integritee-network/teeracle#29]
release a first version of our teeracle SDK nailed to a recent polkadot release 

* [x] write a tutorial how developers can change our teeracle to fetch some trading pair on coinmarketcap (i.e. DOT/USD) and send the data to L1 teeracle pallet (use a fork of our our solochain integritee-node as L1 for simplicity)
  * Existing version on https://integritee-network.gitbook.io/integritee-wiki/for-developers/teeracle
  * In GitBook https://integritee-network.gitbook.io
* [x] README.md in repository references the GitBook
* [x] New release branch version 0.10.0, polkadot 0.9.27

**Comment by echevrier** [comment]
Do the release according to : https://github.com/integritee-network/worker/issues/990
