### ISSUE TITLE
Launch new Teeracle for Integritee parachain on Kusama

### ISSUE THREAD

**Issue by echevrier** [integritee-network/teeracle#34]
on devsg03

**Comment by echevrier** [comment]
Same build as the one tested on rococo:
- commit https://github.com/integritee-network/worker/commit/d8b6b931a33526b27bba18f4bd4f789d8c8c170c
- build on devsgx03
- signed by Zoltan

New Coinmarket Cap API got from Integritee.

**Comment by clangenb** [comment]
This has been deployed 🥳 

Proof: https://integritee.subscan.io/event?address=&module=teeracle&event=exchangerateupdated&startDate=&endDate=&startBlock=&endBlock=&timeType=date&version=26
