### ISSUE TITLE
[monitoring] watch for extrinsic failures and alert if teeracle not working properly

### ISSUE THREAD

**Issue by brenzi** [integritee-network/teeracle#8]
Monitoring requirements:
* teeracle enclave balance alerts
* extrinsic failures
* general service health

**Comment by mosonyi** [comment]
@echevrier can you please help to understand how the teeracle can be checked?

**Comment by brenzi** [comment]
@mullefel is working on prometheus for teeracle
Worker#611

**Comment by murerfel** [comment]
I have an open PR in the worker that needs to be done first: https://github.com/integritee-network/worker/pull/646
Then I'll do an upstream rebase/merge in the teeracle repo and then do the metrics integration for the teeracle ( #9 ).
Is there some urgency in this task? If yes, I will ask @haerdib and @clangenb to prioritize reviewing my PR in the worker.

**Comment by mosonyi** [comment]
Issue moved to [integritee-network/worker #1227](https://github.com/integritee-network/worker/issues/1227) via [**Zenhub**](https://www.zenhub.com/)
